# Generated by Django 5.2.1 on 2025-05-21 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("fulfillment", models.PositiveIntegerField()),
                ("happiness", models.PositiveIntegerField()),
                ("energy", models.PositiveIntegerField()),
                ("stress", models.PositiveIntegerField()),
                ("sleep", models.PositiveIntegerField()),
                ("activity", models.PositiveIntegerField()),
                ("nutrition", models.PositiveIntegerField()),
                ("purpose", models.PositiveIntegerField()),
                ("motivation", models.PositiveIntegerField()),
                ("confidence", models.PositiveIntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
