# Generated by Django 5.2.1 on 2025-05-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="progressentry",
            options={},
        ),
        migrations.AlterField(
            model_name="progressentry",
            name="activity",
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="progressentry",
            name="confidence",
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="progressentry",
            name="energy",
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="progressentry",
            name="fulfillment",
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="progressentry",
            name="happiness",
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="progressentry",
            name="motivation",
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="progressentry",
            name="nutrition",
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="progressentry",
            name="purpose",
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="progressentry",
            name="sleep",
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="progressentry",
            name="stress",
            field=models.IntegerField(default=50),
        ),
    ]
