
name: Build and Deploy Backend

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ACR_NAME: vitalpathregistry
      IMAGE_NAME: vitalpath-backend

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Backend Image
      run: |
        docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:latest ./backend
        docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:latest
