
name: Build and Deploy Frontend

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ACR_NAME: vitalpathregistry
      IMAGE_NAME: vitalpath-frontend

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Frontend Image
      run: |
        docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:latest ./frontend
        docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:latest
