# Generated by Django 5.2.1 on 2025-05-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoverydata",
            name="age",
            field=models.PositiveIntegerField(default=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discoverydata",
            name="baseline_activity",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="discoverydata",
            name="baseline_confidence",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="discoverydata",
            name="baseline_energy",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="discoverydata",
            name="baseline_fulfillment",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="discoverydata",
            name="baseline_happiness",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="discoverydata",
            name="baseline_motivation",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="discoverydata",
            name="baseline_nutrition",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="discoverydata",
            name="baseline_purpose",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="discoverydata",
            name="baseline_sleep",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="discoverydata",
            name="baseline_stress",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="discoverydata",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("non-binary", "Non-binary"),
                    ("prefer-not-to-say", "Prefer not to say"),
                ],
                default=25,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discoverydata",
            name="height_feet",
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discoverydata",
            name="height_inches",
            field=models.PositiveIntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discoverydata",
            name="location",
            field=models.CharField(default="Not specified", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discoverydata",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("married", "Married"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                    ("separated", "Separated"),
                    ("in-relationship", "In a Relationship"),
                    ("prefer-not-to-say", "Prefer not to say"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="discoverydata",
            name="preferred_name",
            field=models.CharField(default="User", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discoverydata",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="discoverydata",
            name="weight",
            field=models.PositiveIntegerField(default=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="discoverydata",
            name="goal_1",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="discoverydata",
            name="goal_2",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="discoverydata",
            name="goal_3",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
